import MainPage from "@/app/(app)/main";
import { ArrowLeftIcon } from "lucide-react";
import Link from "next/link";
import OrderDetail from "./OrderDetail";
import { use } from "react";

export const metadata = {
    title: "Jour Apps - Transaction Detail",
    description: "Generated by create next app",
};
const TransactionDetail = ({ params }) => {
    const { invoice } = use(params);

    return (
        <MainPage headerTitle={"Transaction Detail"}>
            <div className="flex items-center gap-2 mb-4">
                <Link className="underline hover:text-teal-500" href="/inventory">
                    <ArrowLeftIcon />
                </Link>
                <h1 className="text-slate-500">
                    Invoice: <span className="font-bold">{invoice}</span>{" "}
                </h1>
            </div>
            <OrderDetail invoice={invoice} />
        </MainPage>
    );
};

export default TransactionDetail;
